### ISSUE TITLE
Error triggers "Cannot read property 'stack' of null" error in SugarCube code

### ISSUE THREAD

**Issue by HiEv** [tmedwards/sugarcube-2#18]
SugarCube v2.30.0 tested in Opera.

In lib/alert.js it has the following code:
```
		if (typeof error === 'object' && error.stack) {
			mesg += `\n\nStack Trace:\n${error.stack}`;
		}
```
However, "null" is an object, so if "error" is set to "null", then it will get past the "typeof error === 'object'" check, but when it tries to read the "stack" property of "error" it will throw the error:
> Uncaught TypeError: Cannot read property 'stack' of null

To fix this you should do:
```
		if (!!error && typeof error === 'object' && error.stack) {
			mesg += `\n\nStack Trace:\n${error.stack}`;
		}
```
which will work since "null" has a falsy value, while any legitimate object will have a truthy value.

Thanks.

**Comment by tmedwards** [comment]
Where did you encounter this?  The only instances where `error` could be `null` are:

* A `null` value were thrown and never caught anywhere, so eventually bubbled up to the global handler.
* The author manually called `Alert.error()` or `Alert.fatal()` and passed in a `null` value.

The likelihood of either of those happening is infinitesimal.  Not to mention someone doing either would be a huge WTAF in and of itself.

I've patched the issue—because why not—but I'm having a hard time believing that this was factually an issue.

**Comment by HiEv** [comment]
Well, then I ran across an error of "infinitesimal" likelihood.

I was testing Unicode support and tried to load an ANSI file in as though it was UTF-16, and that triggered the bug in SugarCube.  I didn't expect the code to work, but I didn't expect it to cause a problem in SugarCube like that either.

Try it for yourself:
[Null_Bug.zip](https://github.com/tmedwards/sugarcube-2/files/4014510/Null_Bug.zip)

P.S. It's really weird how you keep doubting errors I see almost every time I report them to you.  This is like the third or fourth time you've done this to me now.

**Comment by tmedwards** [comment]
> P.S. It's really weird how you keep doubting errors I see almost every time I report them to you. This is like the third or fourth time you've done this to me now.

I didn't doubt that you encountered something.  I did, in fact, check into and addressed the issue—as I noted in my last reply.  What I had a question about was how you encountered something so unlikely—and yes, believe it or not, `null` being thrown by a browser in lieu of an actual exception is unlikely.

Not to mention that the exact code in question has been in the codebase for nearly ***2.5 years*** and this is the first reported instance.

It's really weird how you keep taking any questions/comments as slights.  If you think that no developer is ever going to have questions about a reported issue, then you're deluding yourself.  In particular, most developers are going to want to reproduce the issue so they can see it firsthand.  So, yes, there will be attempts to reproduce reported issues, questions, testing, etc.  There is nothing strange about this.

**PS:** Your test code has a race condition.  While the debugging property `SugarCube` is added to `window` before startup, its sub-properties are not added to it until the very end of the startup sequence.  Thus, attempting to assign to `SugarCube.setup` might fail depending on when it lands.  For what you're attempting, assigning to a property on `window` would be safer.

**Comment by HiEv** [comment]
> I didn't doubt that you encountered something.

Really?  Because the whole _"The likelihood of either of those happening is infinitesimal"_ part suggests otherwise.

> Not to mention that the exact code in question has been in the codebase for nearly 2.5 years and this is the first reported instance.

There's a difference between "it wasn't reported" and "it's infinitesimally unlikely".

> It's really weird how you keep taking any questions/comments as slights.

Yeah, well, I only do it with you, because you're the only one who keeps treating me like this.

Seriously, I've reported errors tons of times to all sorts of different people, and I've _never once_ gotten as much pushback and defensiveness as I've gotten from you.

> If you think that no developer is ever going to have questions about a reported issue, then you're deluding yourself.

That's not what I think at all, I'm fine with questions.  Just not weirdly accusatory ones.

I simply haven't encountered any other developers who are so quick to dismiss errors that they can't personally reproduce as you do.  One other developer I worked with described you as "prickly", and it's the most apt description of you that I've heard.

Nor have I heard the kind of response that you're giving to me above from anyone else.

Look, this isn't the place to discuss this, but even now you're being overly defensive, when the error that I brought up I was entirely correct about.  You didn't have to make excuses about how "rare" it was or imply how bad a programmer would have to be to invoke such an error, but you did, and that's entirely on you.  Not me.

**Comment by tmedwards** [comment]
The chance of you encountering what you did was very, very small—i.e., ***infinitesimal***—and I explained why that is in my last reply.  I neither said nor implied that you encountered nothing, that you were imagining it, or whatever other negative connotations you've dreamed up.

As far as it being factually an issue.  To use an analogy, if your car had a defect that caused it to spontaneously explode if it came within 100 meters of Gandalf the Grey, then while the defect is a grave issue should it trigger, the likelihood of it actually triggering is fairly small—one could almost say, infinitesimal.  That is what I meant.  That while the underlying issue existed, the odds of it being triggered in the wild were small enough that I found it hard to believe that it was from a normal occurrence.  I did not mean that I believed that you encountered nothing, imagined it, or whatever.

> Yeah, well, I only do it with you, because you're the only one who keeps treating me like this.

And, of course, it's completely my fault.  You're a saint, it's always the other party.

You fixate on the smallest things and either blow them out of proportion or twist them to whatever negative connotation you want.  I've never claimed to be anything like perfect, but your holier than thou attitude really stinks.

Also.  Considering you've jumped down Greyelf's throat before for disagreeing with you, apparently I'm not the only one.  I am probably the only one who refuses to take your shit, so I have that going for me—yay.

> […]  Just not ones with weirdly accusatory asides.

Not assuming that everything you don't like is meant as negatively as you can imagine might help with that.

> I simply haven't encountered any other developers who are so quick to dismiss errors that they can't personally reproduce as you do.

I didn't dismiss this issue—it's fixed (in my local repo), as noted previously.  I also haven't dismissed the audio issue you opened either, even though I haven't been able to reproduce it—hell, I've put time into needlessly attempting to appease Firefox, so it stops emitting the warning.

As far as reproducing an issue goes.  How is anyone supposed to fix something they can't find or understand?  Reproducing an issue, and understanding it, is integral to being able to fix it.  So, yes, I want to be able to reproduce issues—even seemingly simple ones.  Again, this is not unusual.

> Look, this isn't the place to discuss this, […]

Why not?  This is my repo, not a normal public venue—though it is public.  We need to do this someplace and, while not perfect, this seems like a good enough place to me.

> […] but even now you're being overly defensive, […]

Where?  In my very first reply in this issue: I noted that I fixed the issue—meaning that I both verified the issue and accepted that it needed to be fixed.  I also noted the only conditions that could trigger it and further mentioned that the likelihood of that happening was very, very small.  That in turn made be wonder if it was actually an issue in the wild.  I also asked where you encountered it—because of the aforementioned likelihood.  None of that was defensive.

My second reply was a failed attempt at clarification—failed because apparently you'd already decided to be offended, presumably by my use of *infinitesimal*.

> […] when I was entirely correct about the error that I brought up.

I neither said nor implied you were incorrect about the issue.  I had questions about how you'd encountered it.  Those are not the same thing.

> You didn't have to make excuses about how "rare" it was […]

What excuse?  Noting that the chance of it happening in the wild is rare is not an excuse when I'd already accepted and fixed the issue.  If I'd used that to avoid fixing it, then yes, that would have been an excuse.

> […] or imply how bad a programmer would have to be to invoke such an error, but you did, and that's entirely on you. Not me.

No, factually, I did not.  I didn't know how you'd encountered the error, which is why I asked you about it.  I could have simply assumed that you'd done something stupid and not bothered to ask, simply writing you off.  Instead, I asked you how you'd received it.  Fuck me for giving a shit.
