### ISSUE TITLE
.ariaDisabled(true) not affecting tabindex

### ISSUE THREAD

**Issue by MalifaciousGames** [tmedwards/sugarcube-2#219]
**Is your feature request related to a problem?**

Using `.ariaDisabled(true)` on an interactive element doesn't remove it from tab selection as it retains its `tabindex='0'` property.

**Describe the solution you'd like.**

Making disabled elements `tabindex='-1'` would be in line with the hover effect signifying they cannot be selected/interacted with.

**Comment by tmedwards** [comment]
Yeah.  It should probably be doing that.

**Comment by tmedwards** [comment]
This is resolved, so closing the issue is okay. 👍🏻

For future reference, however, I generally close resolved issues myself either automatically by commit message or, failing that, manually.

In this case the `resolves #219` bit in the titles would have triggered auto-closing upon the `develop` branch being merged into `master`.
