### ISSUE TITLE
Autofocus not working on first passage

### ISSUE THREAD

**Issue by manonamora** [tmedwards/sugarcube-2#226]
**Describe the bug.**
The autofocus option from textboxes does work on the first loaded or playable passage. It works as intended if the textbox with autofocus is coded on any other passage (as long as it's not the first)

**To Reproduce:**
1. <<textbox "$pie" "Blueberry" autofocus>> on the first playable passage/
2. Open the passage in browser.

**Expected behavior.**
The autofocus should be working even if it is the first loaded passage.

**Project details.**
 - SugarCube Version: 2.36.1
 - Compiler & Version: Twine 2.6, Tweego 2.1.1

**Desktop details.**
 - OS & Version: Windows 10 & 11
 - Browser & Version: Firefox 111.0 (64-bit)

**Comment by manonamora** [comment]
I was working on something else, and found that the autofocus on the textbox also doesn't work when it is inside a <<timed>> macro.

**Comment by tmedwards** [comment]
It's related, so you get a pass. :)

**Comment by tmedwards** [comment]
And that should fix every delayed insert issue—e.g., `<<replace>>`, `<<type>>`, custom user code, etc.

**Comment by manonamora** [comment]
Hopefully last comment on this (sorry!)
the autofocus doesn't work if the `<<textbox>>` is inside a dialog popup either 😬 
(If this is normal behaviour, maybe to leave a note on the documentation?)

**Comment by tmedwards** [comment]
I'll test it to make sure, but it's probably already been fixed.

Also, a thought.  Are you sure you should be autofocus'ing this much?  Stealing focus from the player is something that should normally be done sparingly, especially if done *after* passage load—e.g., via `<<replace>>`, `<<type>>`, `<<timed>>`, etc.  It *can be* pretty jarring for impaired players that keyboard, rather than mouse.  Just something to consider.

**Comment by manonamora** [comment]
Oh, each report were stuff I noticed on different projects where it's used once or twice :)

**Comment by tmedwards** [comment]
Tested and confirmed fixed inside dialogs as well.
