### ISSUE TITLE
SugarCube UI passage StoryTitle does not support the include macro

### ISSUE THREAD

**Issue by selden** [tmedwards/sugarcube-2#23]
It'd be helpful if the SugarCube UI passage StoryTitle supported the use of the include macro.
All of the other UI passages do support it. See the upper left corner of the attached screengrab.

I'm also including a Zip of the includes.tw file used to demonstrate this problem.
[includes.zip](https://github.com/tmedwards/sugarcube-2/files/4327810/includes.zip)

![capture_005_13032020_000605](https://user-images.githubusercontent.com/353932/76589104-5244e780-64bf-11ea-9501-f278338073cb.png)

Background: I'm trying to simplify as much as possible the .tw file containing the story's text both so I'm not distracted by (and tempted to modify) the SugarCube code and to simplify the translation of the story's .tw file into other formats.

**Comment by tmedwards** [comment]
From [its documentation](http://www.motoslave.net/sugarcube/2/docs/#special-passage-storytitle):
>  **NOTE:** The story title should the project's plain text title and contain no markup.

The `StoryTitle` special passage being treated as plain text is intentional as the story title is currently used as the foundation of SugarCube's storage keys, among other things.  Having it be mutable at all could result in player data loss.  Thus, it's not going to change in v2.
