### ISSUE TITLE
previews passages don't disapear

### ISSUE THREAD

**Issue by metalalchemist** [tmedwards/sugarcube-2#230]
**Describe the bug.**
well when i compile my game and i clicked in any option the previews passage with the other options still is in the game.
with a screen reader (jaws or nvda) i acn read the content of the previews passage and in shugarcube 2.35.0 i can't it
for example.
choose a fruit
[[apple]]
[[orange]]
i clicked in apple and i can read...
choose a fruit
apple disabled
[[orange]]
well you clicked in apple!
**To Reproduce:**
1. compile my game with tweego 2.1.1
2. Click on any passage and it don't disapear.
**Expected behavior.**
i used shugarcube 2.35.0 and the passage disapear for show the clicked passage.
**Screenshots.**
[(https://dl.dropbox.com/s/zkwrra38vr1xbyl/Captura%20de%20pantalla%202023-04-29%2017.06.32.png?dl=0)
**Project details.**
 - SugarCube Version: [2.37.0-alpha.6]
 - Included Add-ons: [e.g., Chapel's Notify Macro, Cyrus' Click to Proceed Macro]
 - Included Libraries: [e.g., Moment.js, Tracery]
 - Compiler & Version: [e.g., Twine 2.3.13, Tweego 2.1.1]

**Desktop details.**
windows 10 latest version.
- Browser & Version [microsoft edge latest version

**Smartphone/tablet details.**
 - Device: [e.g., iPhone Xs Max]
 - OS & Version: [e.g., iOS 14.4]
 - Browser & Version [e.g., Safari 14.4, Firefox for iOS 31]

**Additional context.**

**Comment by metalalchemist** [comment]
i find the problem, the problem is when i put

config.passages.transitionOut = "opacity";

**Comment by greyelf** [comment]
> i find the problem

Do you mean `Config.passages.transitionOut = "opacity"`, with an upper-case **C** in Config?

> SugarCube Version: [2.37.0-alpha.6]

The latest release of SugarCube is **v2.36.1** and I was unable to find a 2.37.0-alpha.6 branch or tag in the official sugarcube-2 Github repository.
Are you compiling your own custom version of SugarCube?
And If so, have you made any unofficial changes to your custom version?

> Screenshots

That image shows that a undefined **MobileAccessibility** reference is being used in some JavaScript code that is being executed within a <<script>> macro. Is that something you are defining in your own code?

As ask because, I searched through the source code of all the JavaScript based libraries you listed (eg. SugarCube, Notify Macro, Click to Proceed Macro, Moment.js, and Tracery,js) and none of them contains a MobileAccessibility reference.

**Comment by metalalchemist** [comment]
sorry, my english is so bad.i refer to a previous passage.
> Do you mean Config.passages.transitionOut = "opacity", with an upper-case C in Config?

yes i rerefer to when i put Config.passages.transitionOut = "opacity" the previous passage can read with a screen reader.
i don't use any library but i based my report in a template.

> The latest release of SugarCube is v2.36.1 and I was unable to find a 2.37.0-alpha.6 branch or tag in the official sugarcube-2 Github repository.
Are you compiling your own custom version of SugarCube?

i compiled since develop branch
but i downloaded shugarcube 2.36.1 and i have the same problem.

> That image shows that a undefined MobileAccessibility reference is being used in some JavaScript code that is being executed within a <<script>> macro. Is that something you are defining in your own code?

yes this is a movile cordova plugin that detect a screen reader but i execute my game since my pc.

**Comment by tmedwards** [comment]
> yes i rerefer to when i put Config.passages.transitionOut = "opacity" the previous passage can read with a screen reader.
Ah, yes.  That's going to happen currently.

I'll add the necessary plumbing to cause accessibility software to ignore the outgoing passage.

**Comment by metalalchemist** [comment]
thanks when you  update it please tellme.
