### ISSUE TITLE
bookmark information missing from documentation for v2.37.0

### ISSUE THREAD

**Issue by selden** [tmedwards/sugarcube-2#287]
**Describe the bug.**

The documentation for SugarCube v2.37.0-alpha.18+10004 says that the special tag ```[bookmark]``` is deprecated but neither describes what it was used for nor what should be used in its place. It would be very helpful if documentation for  both were included.

**Expected behavior.**

A clear and concise description of the replacement.

**Project details.**
 - SugarCube Version:  v2.37.0-alpha.18+10004
 - Included Add-ons: n/a
 - Included Libraries: n/a
 - Compiler & Version:  Tweego 2.1.1

**Desktop details.**
 - OS & Version: Windows 10 Pro x64 22H2 
 - Browser & Version: Firefox/120.0

**Smartphone/tablet details.**
not used

**Additional context.**

I'd like to have the "Jump to" facility continue to be available in the GUIs of my future IFs.

**Comment by tmedwards** [comment]
Other than a brief entry showing they existed at some point, deprecated features are largely removed from the documentation.  The reason being because usage of them is meant to wither and die.

Any replacements are generally noted within the deprecated feature's truncated entry.  In this case, there is no replacement.  The `bookmark` tag and *Jump To* dialog are simply being sunsetted.

They're both deprecated, not removed, so you may continue to use them for now, but they will be gone from v3.
