### ISSUE TITLE
Missing `Engine.show()` after `unmarshallForSave()` is called. 

### ISSUE THREAD

**Issue by SjoerdHekking** [tmedwards/sugarcube-2#291]
I am using `State.unmarshallForSave(StateObject)`, I expect that the title associated with the marshalled object is shown after this function call. 

In 2.36.1, during `State.unmarshallForSave(StateObject)` a call is made to `Engine.show()` which moves to player to the correct title. As seen [here](https://github.com/tmedwards/sugarcube-2/blob/27903a854b7bedbb9fa60efa33e47c99bab7a359/src/save.js#L621)

However, in 2.37.0-alpha.18, during `State.unmarshallForSave(StateObject)` there is no call made to `Engine.show()`.
As seen [here](https://github.com/tmedwards/sugarcube-2/blob/8b244510826ec3c728f09cdcf6fe8ddcef581c7b/src/state.js#L105)

I wonder if there is going to be another new function which should be used instead, or if the function in 2.37.0-alpha.18 is incomplete. Please correct me if I am misunderstanding it!

**Comment by tmedwards** [comment]
You're looking at two completely different functions.

The public `State.unmarshalForSave()` API has never called `Engine.show()`.

The private `Save/unmarshal()` API used to, but that changed, yes.

Since `State.unmarshalForSave()` hasn't changed in this regard, and you've never been able to call `Save/unmarshal()`, what exactly is the problem?

**Comment by SjoerdHekking** [comment]
Fair points.

I try to use `State.unmarshalForSave()` in 2.37.0-alpha.18. After I call this function, I expect to be forwarded to the correct passage, which doesn't happen. If you take a look at my first and second link and compare them you see in 2.36, there is `Engine.show()`, but in the alpha it's missing.

If you want a test case I'd happily supply one!

**Comment by tmedwards** [comment]
> After I call this function, I expect to be forwarded to the correct passage, which doesn't happen.

You are, just as in the current version.  That's what the call to `momentActivate()` at the bottom does.  Now, the newly active moment is not presented/shown to the player by that, but that's true of the current version as well.


> If you take a look at my first and second link and compare them you see in 2.36, there is Engine.show(), but in the alpha it's missing.

I did look at your links.  As I pointed out in my last reply, you're linking to completely different functions, from different APIs, with one not even being callable by you.

You're comparing apples to kumquats by associating a public `State` API with a private `Save` API.

The public `State.unmarshalForSave()` API is served by the functions:

* In `≤v2.36.1`
[`stateUnmarshal()`](https://github.com/tmedwards/sugarcube-2/blob/27903a854b7bedbb9fa60efa33e47c99bab7a359/src/state.js#L120)
* In `≥v2.37.0`
[`stateUnmarshal()`](https://github.com/tmedwards/sugarcube-2/blob/8b244510826ec3c728f09cdcf6fe8ddcef581c7b/src/state.js#L105)

As you can see, that particular API is essentially unchanged between versions.  All calls to it and the resulting behavior will be the same.

I don't know what you think you're seeing by manually calling `State.unmarshalForSave()`, however, neither version updates the screen.

If you are seeing something, then it definitely should not be from calling `State.unmarshalForSave()`.

----

**Question:** Why do you keep attempting to conflate a `State` API with an internal `Save` function?

Yes, the internal only `Save` `unmarshal()` function did change, but it calls `State.unmarshalForSave()` rather than the other way around.  Meaning your calls to `State.unmarshalForSave()` are unaffected.

I really don't understand why you keep pointing at the `Save` function as if it proves some point wrt. the `State` API.

**Comment by tmedwards** [comment]
To be clear.  The only APIs that can call `Save` `unmarshal()` are from `Save` because it's not public.  Meaning the only APIs affected by changes to it are `Save` APIs.

In other words, ***no*** `State` APIs have a dog in that fight, `State.unmarshalForSave()` or otherwise.

**Comment by SjoerdHekking** [comment]
Excuse me for misunderstanding the two. Thanks for your time, I greatly appreciate it. Let's close this issue, for some odd reason, I saw behaviour that indeed doesn't work again after testing in both versions.
