### ISSUE TITLE
Error message when playing story

### ISSUE THREAD

**Issue by BetaTypeCoda** [tmedwards/sugarcube-2#335]
**Describe the bug.**
It opens my browser, but an error message appears and I'm unable to do anything. My stories are made from templates I got from Itch.io, so part of the problem might be them being out of date.

On one of the templates I use, someone was also having the same issues, but they managed to fix it and posted a way to fix it. So far it seems to work but it displays a different error saying, 'config is not defined'. The person suggested to change 'config' to 'Config' in JavaScript to which I did but got this message.

![Screenshot 2024-09-12 145049](https://github.com/user-attachments/assets/74e6bfbc-3780-4eff-931d-28cc31ede4ce)

**To Reproduce:**
1. I use the Twine/Sugarcube 2 Template by a.w. morgan on Itch.
2. Importing it into Twine then playing it will give the error message about the ID 'story' in the interface.
3. Replace every ID 'story' and #story with 'mystory'.
4. After that it'll say, 'config is not defined'.
5. Change 'config' to 'Config' in 'config.saves.autosave = "autosave";' to make the error like in the screenshot to appear.

**Expected behavior.**
Run games. 

**Screenshots.**
![Screenshot 2024-09-12 145038](https://github.com/user-attachments/assets/64e71304-1b83-4f42-a6d0-f99d1f3786dc)
![Screenshot 2024-09-12 145131](https://github.com/user-attachments/assets/201e2e5f-9ee0-48de-8cdf-2e50f7ae0733)

**Project details.**
- SugarCube Version: 2.37.3
- Included Add-ons: None
- Included Libraries: None
- Compiler & Version: Twine 2.9.2

**Desktop details.**
- OS & Version: Windows 11
- Browser & Version: Microsoft Edge Version 128.0.2739.67 and Chrome Version 128.0.6613.138

**Additional context.**
I use story templates from Itch.io. So, I'm thinking them being out of date is the issue.

**Comment by greyelf** [comment]
@BetaTypeCoda 
Because you are now using a 2.37.x version of SugarCube to build your project I strongly suggest you read the 
[Updating to any version ≥2.37.0 from a lesser version](https://www.motoslave.net/sugarcube/2/docs/#guide-code-updates-2.37.0) section of the SugarCube documentation, as it contains answers to your reported issues.

- The **Deprecated legacy APIs** section of that information states the old **config** API has now been removed, which is why you need to use the newer [Config API](https://www.motoslave.net/sugarcube/2/docs/#config-api) instead.
- The **Config API** section of that information states that the **Config.saves.autosave** setting has been replaced with the newer [Config.saves.maxAutoSaves](https://www.motoslave.net/sugarcube/2/docs/#config-api-property-saves-maxautosaves) setting.

**Comment by tmedwards** [comment]
↑ That.  Greyelf has the right of it.

Additionally.  You have `config.saves.autosave` in there twice, with different values no less.  It is not helpful to have multiple versions of the same configuration value.

Assuming you want the second version, because that's the version that's taking effect now, you want something like this:

```
Config.saves.maxAutoSaves = 1;
Config.saves.isAllowed = function (saveType) {
	return !tags().includes('noreturn');
};
```

----

And as to the second error you received, it tells you exactly what's wrong.  It's coming from the first version you have:

```
config.saves.autosave = "autosave";
```

Is `"autosave"` any of the types listed in the error?  No.  It's neither a `boolean` (`true` or `false`), an `Array<string>` (array of strings), a `function`, or a nullish value (`null` or `undefined`).  It is a `string` value, which the error also tells you.  Hence, the error.
