### ISSUE TITLE
Empty star is missing in new icon font

### ISSUE THREAD

**Issue by Arkerthan** [tmedwards/sugarcube-2#336]
**Is your feature request related to a problem?**
Currently porting a game to 2.37, noticed the empty star (old code 0xe801) does not exist in the new icon set.

Is there any particular reason for this?

**Describe the solution you'd like.**
The empty star is readded.

**Describe alternatives you've considered.**
Pull in my own fontawsome subset.

In this case a note in the "Code Updates" section of the guide would be appreciated. (I'd argue icons going missing is a breaking change)

**Additional context.**
Relevant commit: https://github.com/tmedwards/sugarcube-2/commit/e776abaa07e2350241d0420df351033ecdbb4406

**Comment by tmedwards** [comment]
In the very commit you linked to the description reads:

> * Update icon font and all references to it.
> * Add icon font reference guide to the documentation.

If we look at the documentation we find: [Guide: Icon Font](https://www.motoslave.net/sugarcube/2/docs/#guide-icon-font).

The icon is still there it just changed position—well, and name.  As to why the icons changed position, previously they had custom IDs, but with this update they have the IDs assigned by Font Awesome.

**Comment by Arkerthan** [comment]
Which is missing the equivalent for `icon-star-empty` (`0xe801`). https://www.motoslave.net/sugarcube/tmp/tme-fa-icons/

If I'm wrong just tell me the ID, but I've looked through that list several times and cannot find it.

**Comment by greyelf** [comment]
Font Awesome 6 (and possible earlier versions) use [font-weight](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) to control if a glyph like Star is shown "full", or as one of the three possible variations of "empty". This is why all four variations of the Star glyph have the same numerical identifier of `f005`
eg, solid is **900**, regular is **400**, light is **300**, and thin is **100**.

I however was not able to get **font-weight** to control the behaviour of the **sc-icon** font, possible because it doesn't have weight based variations of itself, or possible because my CSS-fu is weak. :)
