### ISSUE TITLE
Serial bug

### ISSUE THREAD

**Issue by Valen-H** [tmedwards/sugarcube-2#338]
The newly-introduced `Serial` API does not exist in Scope.
JS code cannot access it and it also cannot be found through the browser console (there is no `SugarCube.Serial` on global).
Did you forget to export/globalize it?

**Comment by greyelf** [comment]
@Valen-H When you say "does not exist in Scope.", do you mean rhat API cant be accesses within:

1. the Private Scope contexts that SugarCube's engine creates to execute JavaScript code defined within:
  - a project's Story JavaScript (or TWEE equivalent) area.
  - JavaScript executing macros like `<<script>>` or `<<run>>`.
  - handlers listening for SugarCube [Events](http://www.motoslave.net/sugarcube/2/docs/#events) like `:passagerender` and `:dialogopened`

2. Private Scoped contexts created by the web-browser itself to execute things like: Console commands; a handler assigned to the `onclick` attribute of a HTML element; or JavaScript code contained within a script added via TweeGo's module option.

Because if you mean the 2nd, then none of the SugarCube APIs are available within those Private Scoped contexts.

**Comment by Valen-H** [comment]
Turns out it was a bug with Tweego mixing old versions (from other directory) and new ones (after checking `SugarCube.version` I noticed it was different each time).
I cleaned my environment and fixed the PATH and now it seems to work.

Sorry for bothering you.
