### ISSUE TITLE
Vendor updates

### ISSUE THREAD

**Issue by HiEv** [tmedwards/sugarcube-2#40]
Most vendor files appear to not be up-to-date:
FileSaver v??? -> [v2.0.3](https://github.com/eligrey/FileSaver.js)
classList v??? -> [v1.2.20180112](https://github.com/eligrey/classList.js) (probably?)
es5-shim v4.5.13 -> [v4.5.14](https://github.com/es-shims/es5-shim)
es6-shim v0.35.4 -> [v0.35.5](https://github.com/paulmillr/es6-shim)
imagesLoaded v4.1.0 -> [v4.1.4](https://github.com/desandro/imagesloaded)
jQuery v3.4.1 -> [v3.5.1](https://jquery.com/download/)
lz-string v1.3.3 -> [v1.4.4](https://github.com/pieroxy/lz-string/)
normalize.css v3.0.3 -> [v8.0.1](https://github.com/necolas/normalize.css)
seedrandom.js v2.3.3 -> [v3.0.5](https://github.com/davidbau/seedrandom)

Not sure how many of these you want to update, but the jQuery update included a security fix.

**Comment by tmedwards** [comment]
> Most vendor files appear to not be up-to-date:

Some of that is by design.  In particular: `FileSaver`, `lz-string`, `normalize.css`, `seedrandom.js`.  The updates to these have generally been either adding unnecessary functionality, moving functionality away from SugarCube's needs, or simply developer churn.  In specific cases—e.g., `lz-string`—there's also the worry that changes could result in data loss.

I'll take a closer look anyway, but I doubt I'll do much updating here.


> es6-shim v0.35.4 -> [v0.35.5](https://github.com/paulmillr/es6-shim)

Ignoring this as the only material update was to the shams, which SugarCube does not include.


> classList v??? -> [v1.2.20180112](https://github.com/eligrey/classList.js) (probably?)

`1.2.20171210` was the last code update.  `1.2.20180112` was just a devel update.

Not sure which version is currently vendored, since the bundled comment doesn't specify, and I didn't edit it as I usually do when the library authors don't do it themselves—which implies it's probably pretty old.

I'll update to `1.2.20171210` and edit the bundled comment to denote to the release.


> es5-shim v4.5.13 -> [v4.5.14](https://github.com/es-shims/es5-shim)
> imagesLoaded v4.1.0 -> [v4.1.4](https://github.com/desandro/imagesloaded)
> jQuery v3.4.1 -> [v3.5.1](https://jquery.com/download/)

Updating.
